spring:
  application:
    name: idempotency-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/idempotency_service
      database: idempotency_service

server:
  port: 8080

logging:
  level:
    microservices.helper.idempotency: INFO
    org.springframework.data.mongodb: INFO
    root: INFO

idempotent:
  lock-duration: 1m # Default lock for one operation is 1 minute
  scheduling:
    expired-lock-removal-rate: 0 */30 * * * *